name: jetu.driver
description: A new Flutter project.
publish_to: 'none'
version: 2.3.4+0

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_vector_icons: ^1.0.0
  yandex_mapkit: ^3.4.0
  firebase_analytics: ^10.0.5
  firebase_auth: ^4.1.2
  firebase_crashlytics: ^3.0.5
  firebase_core: ^2.2.0
  firebase_remote_config: ^3.0.5
  firebase_app_check: ^0.1.1+4
  firebase_core_platform_interface: 4.5.2

  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.12
  mask: ^1.0.4
  fluttertoast: ^8.1.1
  pinput: ^2.2.31
  get_it: ^7.2.0
  mapbox_search: ^3.0.1+2
  supabase: ^1.11.0
  loader_overlay: ^2.1.0
  map_launcher: ^2.5.0+1
  lottie: ^2.0.0
  store_redirect: 2.0.1
  app_version_update: ^4.0.1
  flutter_cupertino_date_picker_fork: ^1.0.7

  routing_client_dart: ^0.3.1
  mapbox_api: ^1.0.0

  sliding_up_panel: ^2.0.0+1
  easy_debounce: ^2.0.2+1
  flutter_screenutil: ^5.8.4
  modal_bottom_sheet: ^3.0.0-pre
  dotted_line: ^3.1.0

  dio: ^4.0.6
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2

  # geo
  flutter_local_notifications: 
  flutter_launcher_icons: ^0.13.1
  background_location: ^0.11.8
  flutter_map: ^0.14.0
  # flutter_map_location_marker: ^3.1.0
  latlong2: ^0.8.1
  geolocator: ^11.0.0
  # location: ^4.4.0
  geocoding: ^2.0.5
  osm_nominatim: ^2.0.1

  auto_route: ^5.0.4
  just_audio: ^0.9.33

  path: ^1.8.0
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.0
  dotted_border: ^2.0.0+3
  nhost_storage_dart: ^1.0.0
  nhost_flutter_auth: ^3.0.0
  uuid: ^3.0.7
  webview_flutter: ^3.0.0
  fl_chart: ^0.60.0 

  firebase_messaging: ^14.2.1
  # geolocator: ^8.2.1



  #credit_card_scanner: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: 2.3.3
  auto_route_generator: 5.0.3
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/jetu_logo.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/icons/
    - assets/lottie/